export const LOCATIONS = [
  "wakefield",
  "castleford",
  "pontefract",
  "garforth",
  "rothwell",
  "boston-spa",
  "tadcaster",
  "collingham",
  "spofforth",
  "clifford",
  "thorp-arch",
  "walton",
  "bardsey",
  "east-keswick",
  "scarcroft",
  "harewood",
  "aberford",
  "pannal",
  "alwoodley",
  "yorkshire",

  "leeds",
    "harrogate",
    "horsforth",
    "ilkley",
    "otley",
    "knaresborough",
    "linton",

  "york",
    "selby",
    "malton",
    "tadcaster",
    "pocklington",
    "elvington",
    "welburn",
    "stamford-Bridge",
    "towton",
    "wetherby",

  "ripon",
    "thirsk",
    "masham",
    "boroughbridge",

  "harrogate",
    "ripley",
    "follifoot",
];

export const NEARBY_LOCATIONS: Record<string, string[]> = {
  default: [
    "york",
    "leeds",
    "harrogate",
    "wetherby",
    "linton",
    "boston-spa",
    "collingham",
    "spofforth",
    "bramham",
  
  ],
  leeds: [
    "york",
    "harrogate",
    "knaresborough",
    "garforth",
    "rothwell",
    "horsforth",
    "ilkley",
    "otley",
    "skipton",
    "wetherby",
  ],
  york: [
      "selby",
      "malton",
      "tadcaster",
      "pocklington",
      "elvington",
      "welburn",
      "stamford-Bridge",
      "towton",
      "wetherby",
      "leeds",
    ],

    ripon: [
      "thirsk",
      "masham",
      "boroughbridge",
      "leeds",
      "york",
      ],
      harrogate: [
        "knaresborough",
        "spofforth",
        "pannal",
        "ripley",
        "follifoot",
        ],
  


};
